### ISSUE TITLE
recent upgrade broke book import

### ISSUE THREAD

**Issue by anarcat** [flathub/com.calibre_ebook.calibre#101]
I'm getting a permission denied on all books since a recent upgrade. I tried to run with `flatkap run --filesystem=host`, to no avail. What am I missing? Is this related to #51?

The error I get from the calibre GUI is: "calibre, version 5.25.0
ERROR: Cannot add books: You do not have permission to read any of the selected files"

**Comment by Erick555** [comment]
Did you mean Add books option? It still works for me. Calibre already has `--filesystem=host` nothing changed there.

You may try running `flatpak update --commit=875dab8d991405ee88bb32b819e3736d98549bfe9fbd2dce7b59388173444747 com.calibre_ebook.calibre` to downgrade to 5.24 and see if this is caused by calibe upgrade or something else changed on your system.

**Comment by anarcat** [comment]
> Did you mean Add books option? It still works for me. Calibre already has `--filesystem=host` nothing changed there.

yeah, it's really odd.

> You may try running `flatpak update --commit=875dab8d991405ee88bb32b819e3736d98549bfe9fbd2dce7b59388173444747 com.calibre_ebook.calibre` to downgrade to 5.24 and see if this is caused by calibe upgrade or something else changed on your system.

I was actually having the issue with 5.20 and *upgraded* to 5.25 to see if it would fix it.

I now suspect this might be an issue with the Debian bullseye upgrade, because I was able to fix the issue by restarting the portal daemon. I'll close this until I get clear confirmation, sorry for the noise, and thanks for the quick response!
